version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: "app_database_dev"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "0000"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "app_pma_dev"
    ports:
      - 8085:80
    environment:
      PMA_HOST: "database"
      PMA_USER: "root"
      PMA_PASSWORD: "0000"
      UPLOAD_LIMIT: "128M"
      PMA_ARBITRARY: 1
    restart: always
    volumes:
      - /sessions
    links:
      - database