ADMIN: ~

CONTACT_MANAGER:
  - CONTACT_CREATE
  - CONTACT_UPDATE
  - CONTACT_GET
  - CONTACT_LIST
  - CONTACT_DELETE

CONTACT_MANAGER_RO:
  - CONTACT_GET
  - CONTACT_LIST

PRODUCT_MANAGER:
  - PRODUCT_ALL
  - PRODUCTCODE_ALL
  - PRODUCTPRICE_ALL
  - PRODUCTTAG_ALL

PRODUCT_MANAGER_RO:
  - PRODUCT_GET
  - PRODUCT_LIST
  - PRODUCTTAG_GET
  - PRODUCTTAG_LIST

HISTORY_RO:
  - SALE_GET
  - SALE_LIST
  - SALEPAYMENT_GET
  - SALEPAYMENT_LIST
  - SALEPAYMENT_CREATE
  - SALEPAYMENT_DELETE

HISTORY:
  - SALE_GET
  - SALE_LIST
  - SALE_UPDATE
  - SALEPAYMENT_GET
  - SALEPAYMENT_LIST
  - SALEPAYMENT_CREATE
  - SALEPAYMENT_DELETE

STATS:
  - STATS_GET
  - STATS_LIST

POS:
  - CONTACT_GET
  - CONTACT_LIST
  - PRODUCT_GET
  - PRODUCT_LIST
  - PRODUCTTAG_GET
  - PRODUCTTAG_LIST
  - SALE_CREATE
  - SALE_REVERT

WEBSITE:
  - PRODUCT_GET
  - PRODUCT_LIST
  - PRODUCTTAG_GET
  - PRODUCTTAG_LIST
